global:
  width: 50            # map width [m] 
  height: 50           # map height [m] 
  resolution: 0.05     # resolution [m/cell] 
  updateEveryNthLidar: 2  # update costmap every Nth lidar (= lidar frequency / costmap update frequency)

local:
  width: 5             # map width [m]
  height: 5            # map height [m]
